//
//  FruitsAndBerriesModels.swift
//  iOS-Test
//

import Alamofire

enum FruitsAndBerriesModels {
    
    static let baseUrl: String = "https://test-task-server.mediolanum.f17y.com"
    
    // Models for "load (list)" use case
    struct Load {
        
        // Request is passed to Interactor
        struct Request {
            var webUrl: String
        }
        // Response is passed from Interactor to Presenter
        struct Response: Decodable {
            let title: String?
            let items: [ItemOfList]?
            let error: String?
        }
        // View model is generated by Presenter and passed to View
        struct ViewModel {
            let hasError: Bool
            let title: String
            let items: [ItemOfList]
            let error: String
        }
        
        //Item of fruit or berry
        struct ItemOfList: Decodable {
            let id: String
            let name: String
            let image: String
            let color: String
        }
        
    }
    
    // Models for "load (detail)" use case
    struct LoadDetail {
        // Request is passed to Interactor
        struct Request {
            var itemId: String
        }
        // Response is passed from Interactor to Presenter
        struct Response: Decodable {
            let id: String?
            let text: String?
            let error: String?
        }
        // View model is generated by Presenter and passed to View
        struct ViewModel {
            let hasError: Bool
            let text: String
            let error: String
        }
    }
}
